baseURL = "https://kan19.github.io/"
languageCode = "en-us"
title = "Ronald The Intern"
theme = "hugo-theme-mini"
defaultContentLanguage = "en"
hasCJKLanguage = true
paginate = 5
googleAnalytics = "your-google-analytics-id"
disqusShortname = "your-disqus-shortname"

[permalinks]
posts = "/posts/:title/"

[markup.highlight]
guessSyntax = true
style = "emacs"

[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 2

[markup.goldmark.renderer]
unsafe = true

[social]
github = "https://github.com/KAN19"
linkedin = "https://www.linkedin.com/in/kiet-nguyen-943564201/"

[params]
author = "Kiet (Ronald) Nguyen"
bio = "Commiting to learn and growth continuously 🚀"
description = "My Blog"
enableRSS = true
enableComments = false
enableGoogleAnalytics = true
showToc = true
showPowerBy = true
math = false
hiddenPostSummaryInHomePage = false
copyright = "KAN19"
